### ISSUE TITLE
[USER STORY]: As a medical patient, I would like to be able to register my account.

### ISSUE THREAD

**Issue by gkillick** [KrisTheCanadian/Protect-Together#11]
## About this story

**Priority**: High
**Story Points**: Fibonacci Sequence: 8
**Risk**: Low

**Description**:
Register a medical patient to the application. 

Fields:
- first and last name
- email
- password
- phone number (??)
- date of birth (??)
- sex (??)
- weight (optional)
- height (optional)
- health card number
- medical conditions (optional)
- additional notes (optional) 

**Exit Criteria**
Users should be able to register for the application, and an account will be created on their behalf with the right permissions. He/She will then be re-directed to the dashboard.

**Acceptance Test**
- Link to the signup page is provided on the login page
- Users can fill out the form on the signup page
- oAuth option for sign up
- Form verifies the appropriate password
- Form verifies unique email
- On submit or OAuth sign up, if all verifications are successful, a new user is created

**Sub-Tasks/Steps**
- [x] Design the 'add new medical patient'  UI 
- [x] Create medical patient record in firebase
- [x] Option to sign up with oAuth
- [x] Create a profile.
- [x] Validate form
- [x] Create medical patient interface
- [x] Testing

**Linked to Issue**: #10
