### ISSUE TITLE
[USER STORY]: As a user, I would like to be able to modify my account settings

### ISSUE THREAD

**Issue by martinsenecal** [KrisTheCanadian/Protect-Together#12]
## About this story

**Priority**: Medium
**Story Points**: 8
**Risk**: Low

**Description**:
The user would be able to edit his own account information. The form will let the user change his medical info and access other settings such as medical conditions, healthcare number, pswd modification, etc. This account setting feature should be visible in the navbar.

**Exit Criteria**
What should we expect once the task is complete:
-Users will be able to edit their own information.
-Validation of inputs in the form is working well.

**Sub-Tasks/Steps**
- [x] Design and code the form in the UI
- [x] Add option in the nav-bar
- [x] Create backend logic
- [x] Add Form Validation (frontend-side/backend-side)

**Additional context**

**Linked to Issue**: #10
