### ISSUE TITLE
[USER STORY]: As a user, I would like to be able to login.

### ISSUE THREAD

**Issue by martinsenecal** [KrisTheCanadian/Protect-Together#14]
## About this story

**Priority**: [High]
**Story Points**: 5
**Risk**: [High]

**Description**:
The user should be able to login onto his account (with his email/password or OAuth). If it's a new account (medical staff, admins, or 3rd party) -> login will act as an activation. If the user doesn't have an activated account (and is a staff), a message will appear to tell them to contact X in order to get access.

**Exit Criteria**
What should we expect once the task is complete:
-Users can log in from the login page
-Error Messages are shown for unsuccessful attempts
-On successful login, the user has access to his/her page on the site.
-Local Storage Token
-Accessing pages other than the login/signup page without being logged in is prevented.

**Sub-Tasks/Steps**
- [x] Design the Sign-In UI
- [x] Create a request to the back end sending the input from the user's id and pswd and comparing it with the info from the database.
- [x] If authentication is correct, create a request to the backend sending the current user's id and returning his account.
- [x] If authentication is incorrect, request the user to input his info again.
- [x] Fixed Auth for Permission
- [x] Password Reset
- [x] Add Tests

**Additional context**

**Linked to Issue**: #10
