### ISSUE TITLE
[USER STORY]: As an admin, I would like to be able to create another admin account.

### ISSUE THREAD

**Issue by martinsenecal** [KrisTheCanadian/Protect-Together#15]
## About this story

**Priority**: Low
**Story Points**: 3
**Risk**: Low

**Description**:
Create additional admin accounts for the application. Creating another admin account will be possible directly from the admin dashboard. A menu will appear prompting the user to choose what type of account to create. Then, a form will appear to add information about the new user (all his info: email, etc). From there, a new user will be created to the database, and this email will be added to the admin user's list.

**Exit Criteria**
-New Admin Account Created in the DB with the right access.

**Sub-Tasks/Steps**
- [x] Create a button to create in the admin dashboard.
- [x] Create UI Form (to fill all missing info)
- [x] Add the users to the right authenticated list (for permission)
- [x] Send an Email Invite to the new user to activate his account and create a pswd.
- [x] Add Form Validation (frontend-side/backend-side)

**Linked to Issue**: #10
