### ISSUE TITLE
[USER STORY]: As a professional (admin, medical staff, 3rd party), I would like to be able to activate my account.

### ISSUE THREAD

**Issue by gkillick** [KrisTheCanadian/Protect-Together#16]
## About this story
**Priority**: [Medium]
**Story Points**: Fibonacci Sequence: 8
**Risk**: Low

**Description**:
Register professional to the application. After clicking on the activation link via email, they should be redirected to the login form asking them to create a pswd and activate the account. Note that the activation will be done automatically (by clicking on the link and adding a pswd, the user will be added automatically with the right permissions into the right environment).

If the user doesn't have an activated account (and is a staff) and is trying to log in, a message will appear to tell them to contact X in order to get access.

**Exit Criteria**
Professionals should be able to register for the application

**Sub-Tasks/Steps**
- [x] Design the activate professional account UI
- [x] Activate professional account in firebase
- [x] Create a pswd.
- [x] Option to sign up with oAuth
- [x] Form Validation
- [x] Testing for the Full Account Creation/Activation Process

**Additional context**

**Linked to Issue**: [#10 ]
