### ISSUE TITLE
[USER STORY]: As an admin, I would like to create a medical staff account.

### ISSUE THREAD

**Issue by gkillick** [KrisTheCanadian/Protect-Together#17]
## About this story

**Priority**: [High/Medium/Low]
**Story Points**: Fibonacci Sequence: 5
**Risk**: Medium

**Description**:
Create additional medical staff accounts for application. Creating a medical staff account will be possible directly from the admin dashboard. A menu will appear prompting the user to choose what type of account to create. Then, a form will appear to add information about the new user (all his info: email, etc). From there, a new user will be created to the database, and this email will be added to the medical staff user's list.

**Exit Criteria**
Admin should be able to add a medical staff to the application.

**Sub-Tasks/Steps**
- [x] Create a button to create in the admin dashboard.
- [x] Create UI Form (to fill all missing info)
- [x] Add the users to the right authenticated list (for permission)
- [x] Send an Email Invite to the new user to activate his account and create a pswd.
- [x] Add Form Validation (frontend-side/backend-side)

**Additional context**

**Linked to Issue**: #10
