### ISSUE TITLE
[USER STORY]: As an admin, I would like to be able to create another 3rd party account

### ISSUE THREAD

**Issue by gkillick** [KrisTheCanadian/Protect-Together#18]
## About this story

**Priority**: High
**Story Points**: Fibonacci Sequence: 5
**Risk**: High

**Description**:
Create additional 3rd party accounts for the application. Creating a 3rd party account will be possible directly from the admin dashboard. A menu will appear prompting the user to choose what type of account to create. Then, a form will appear to add information about the new user (all his info: email, etc). From there, a new user will be created to the database, and this email will be added to the 3rd-party user's list.

**Exit Criteria**
What should we expect once the task is complete:
-admin should be able to add 3rd party users to the application
-email should be sent to added 3rd party users prompting the user to choose his own password and activate his account.

**Sub-Tasks/Steps**
- [x] Create a button to create in the admin dashboard.
- [x] Create UI Form (to fill all missing info)
- [x] Add the users to the right authenticated list (for permission)
- [x] Add Form Validation (frontend-side/backend-side)
- [x] Send an Email Invite to the new user to activate his account and create a pswd.

**Additional context**

**Linked to Issue**: #10
