### ISSUE TITLE
[USER STORY]: As a patient I want my doctor to be notified if my status changes.

### ISSUE THREAD

**Issue by kimdera** [KrisTheCanadian/Protect-Together#20]
## About this story

Priority: High
Story Points: Fibonacci Sequence: 3
Risk: Low

**Description**:
A notification can be sent to a patient's doctor when a  patient re-updates their status.

**Exit Criteria**
A doctor should receive a notification from their patient's status update. 
After the patient submits the status changes, the patient will view a popup indicating "your doctor has been notified about your status update".

Acceptance Test
- Notification Center on the application functions properly
- The title and description of the notification are correct

**Sub-Tasks/Steps**

- [x] Design the notification 
- [x] Database should be updated depending on the notififcation's check box value
- [x] Create a notification center interface
- [x] Testing

**Linked to Issue**: #19
