### ISSUE TITLE
[USER STORY]: As patient I'd like to be notified for any updates on my "case". 

### ISSUE THREAD

**Issue by kimdera** [KrisTheCanadian/Protect-Together#21]
## About this story

Priority: Medium
Story Points: Fibonacci Sequence: 3
Risk: Low

**Description**:
As a patient, I want to be able to get notified if there are any updates on my "medical case" such as getting a new doctor, getting a new appointment, etc. 

I also want to let my doctor know that he has a new patient!

I also want to make sure that the patient can only book an appointment if I give him the permission (bug)

**Exit Criteria**
The patient/doctor has received a notification.

Acceptance Test
- Notification Center on the application functions properly
- The title and description of the notification are correct

**Sub-Tasks/Steps**

- [x] Design the notification UI/Frontend
- [x] Create a notification center interface
- [x] Testing
- [x] Receive Email Notification for Important Notifications about my doctor.

**Linked to Issue**: #19
