### ISSUE TITLE
[USER STORY]: As a user I want to receive a notification if another user sends me a message.

### ISSUE THREAD

**Issue by kimdera** [KrisTheCanadian/Protect-Together#22]
## About this story

Priority: High
Story Points: Fibonacci Sequence: 5
Risk: Low

**Description**:
When a new message is sent to a doctor or a patient they should be notified.

The notification settings for a patient or a medical staff will be different.

**Exit Criteria**
A user should have received a notification indicating that they have received a new message from another user.

**Sub-Tasks/Steps**

- [x] Design the notification UI (figma)/Frontend
- [x] Database should be updated each time a new messenge is sent 
- [x] Add messaging notifications to the notification center interface
- [x] Testing

**Linked to Issue**: #19
