### ISSUE TITLE
[USER STORY]: As a patient, I would like to see my upcoming appointments.

### ISSUE THREAD

**Issue by MilitsaB** [KrisTheCanadian/Protect-Together#28]
## About this story

**Priority**: Low
**Story Points**: Fibonacci Sequence: 5
**Risk**: Low

**Description**:
When a patient has booked an appointment, he can see the date and time on a calendar. (only 1 appointment at a time)

**Exit Criteria**
What should we expect once the task is complete:
- Patient should be able to see all booked appointments.
- Patient should be able to cancel his appointments.
- Patient should be able to see the date and time for each appointment.
- Patient should be able to see a calendar with upcoming appointments.

**Sub-Tasks/Steps**

- [x] Create UI on Figma
- [x] Block the patient to book another appointment until the current appointment is done.
- [x] Display a calendar on User Dashboard 
- [x] Create a request to the backend to retrieve appointment information from the database.
- [x] Display the time and date of each appointment
- [x] Button to delete appointment
- [x] Testing

**Additional context**

**Linked to Issue**: [#31 ]
