### ISSUE TITLE
[USER STORY]: As a patient, I would like to ask for help

### ISSUE THREAD

**Issue by samimerhi** [KrisTheCanadian/Protect-Together#29]
## About this story

**Priority**: High
**Story Points**: Fibonacci Sequence: 13
**Risk**: Low

**Description**:
As a patient, I would like to request some help in regards to my symptoms/current situation. In order to do that, the patient will fill out an "interactive" form that will show answers based on the patient's queries. If these answers are not enough, and/or the situation is too technical -> the patient will be re-directed to a "case" where he/she will be in charge by medical staff. From there, a new "case" will be created and he/she will be able to chat with medical staff.

**Exit Criteria**
What should we expect once the task is complete:
- A patient should be able to fill out a medical form indicating what covid symptoms they have. If the interactive form is not enough, then a patient will be assigned to a doctor.

**Sub-Tasks/Steps**

- [x] Make a symptoms checklist by consulting with a doctor
- [x] Make a responsive form (interactive)
- [x] Add Form Validation (frontend-side/backend-side)
- [x] If a patient needs support from medical staff, redirect it to the creation of a new "medical case" with the triage.

**Linked to Issue**: [#31]
