### ISSUE TITLE
[USER STORY]: As a patient (taken in charge by a medical staff), I would like to update my symptoms and Covid-19 status

### ISSUE THREAD

**Issue by MilitsaB** [KrisTheCanadian/Protect-Together#32]
## About this story

**Priority**: Medium
**Story Points**: 13
**Risk**: Medium

**Description**:
A patient needs to be able to update his Covid-19 status and his symptom to be able to have accurate daily information on his profile for the medical staff when he is taken in charge.

**Exit Criteria**
What should we expect once the task is complete:
- Patients should be able to see their current status and symptoms and modify it.
- Patients should be able to send fill out a new medical form.
- Medical Staff should be able to see the new data (while also still being able to see the old data).

**Sub-Tasks/Steps**

- [x] Display patients symptoms and Add a button to Update
- [x] Create a request to the backend to retrieve update the information in the database.
- [x] Display updated information for medical staff
- [x] Add Form Validation (frontend-side/backend-side)
- [x] Add Tests

**Linked to Issue**: [#31]
