### ISSUE TITLE
[USER STORY]: As a patient, I want to chat with medical staff.

### ISSUE THREAD

**Issue by samimerhi** [KrisTheCanadian/Protect-Together#33]
## About this story

**Priority**: Medium
**Story Points**: Fibonacci Sequence: 13
**Risk**: Medium

**Description**:
If the resources on the patient dashboard do not answer the patient's questions or concerns, they may request to chat with medical staff. This connection will be already implemented in a previous epic. Here, we are asking to create that "chat" component between a patient and a doctor. The chat should be real-time (no need to refresh to view new messages).

**Exit Criteria**
What should we expect once the task is complete:
- A chat system where a patient can communicate with a medical staff.
- The patients/medical staff should be notified when they get a new message.

**Sub-Tasks/Steps**
- [x] Design UI chat module
- [x] Design Page for Patient (similar to Doctor's View)
- [x] Create Chat System Logic (DB)
- [x] Create Real-Time Message System
- [x] Add Message Validation (frontend/backend)
- [x] Add Tests

**Linked to Issue**: [#35 ]
