### ISSUE TITLE
[USER STORY]: As a patient, I would like to get more information about Covid-19 and additional resources.

### ISSUE THREAD

**Issue by samimerhi** [KrisTheCanadian/Protect-Together#36]
## About this story

**Priority**: Low
**Story Points**:  5
**Risk**: Low

**Description**:
On the patients' dashboard, they will be able to see news and information concerning Covid-19 and additional resources like health tips and recommendations.

**Exit Criteria**
What should we expect once the task is complete:
- A section on the dashboard where Covid-19 news is displayed
- A section on the dashboard that displays additional resources

**Sub-Tasks/Steps**

- [x] Link to Covid-19 API
- [x] Research health tips and recomendations
- [x] Create a news section on patient dashboard
- [x] Create a additional statistics section on patient dashboard

**Linked to Issue**: [#31]
