### ISSUE TITLE
[USER STORY]: As patient, I would like to book an appointment with a doctor.

### ISSUE THREAD

**Issue by MilitsaB** [KrisTheCanadian/Protect-Together#37]
## About this story

**Priority**: Medium
**Story Points**: Fibonacci Sequence: 13
**Risk**: Low

**Description**:
A patient should be able to book an appointment and see the doctor's availability. He/She will receive this invitation to book an appointment with the doctor. This prompt will ask him/her to select a timeslot. As soon as this is done, the appointment will be booked in the system and the user will be able to see it in the dashboard. 

**Important: Booking Appointments will only be accessible when the doctor gives permission. (in other words: button will only be visible after the medical staff invite the patient to book an appointment)

**Exit Criteria**
What should we expect once the task is complete:
- The patient can see his booked appointment
- The doctor can see the patient's appointment on his schedule
- After the date, the appointment changes from "upcoming appointment" to "the previous appointment"

**Sub-Tasks/Steps**

- [x] Design UI on Figma
- [x] Create a UI for booking appointments
- [x] Create request to backend to add appointment to database.
- [x] Create request to backend to update appointment status to database.
- [x] Add Form Validation (frontend-side/backend-side)
- [x] Add Tests

**Additional context**

**Linked to Issue**: [#38]
