### ISSUE TITLE
[USER STORY]: As a medical staff, I want to be able to see my list of patients in a table

### ISSUE THREAD

**Issue by fadi-albasha** [KrisTheCanadian/Protect-Together#43]
## About this story

**Priority**: High
**Story Points**: 13
**Risk**: Low

**Description**:
Medical staff should see all their patients on a list where high-priority patients are shown at top of the list. Medical staff should be able to distinguish between visited and unvisited profiles. They should also be able to sort their list of patients based on multiple factors (symptoms, age, covid status, appointment date, etc). When clicking on a patient on the table, the medical staff will be re-directed to the "patient file" where he/she will be able to see all the info and chat with him/her.

**Exit Criteria**
-All lists of patients appear in a list (Table)
-Patients with higher priority should appear at top of the list.
-After visiting a patient's profile, its entry in the list shows in a different color than those not visited.
-Sorts will work.

**Sub-Tasks/Steps**
- [x] Add Tests
- [x] Show visited patient profile elements in the list in a different color
- [x] Show a list of all patients where high priority patients appear first
- [x] Build UI Table
- [x] Build Logic to get all data.
- [x] Build Search and Sorts System
- [x] Redirect each patient to their own "page-status".

**Linked to Issue**: [#42]
