### ISSUE TITLE
[USER STORY]: As a medical staff, I want to view a patient's medical info

### ISSUE THREAD

**Issue by fadi-albasha** [KrisTheCanadian/Protect-Together#44]
## About this story

**Priority**: High
**Story Points**: 8
**Risk**: Medium

**Description**:
Medical staff should be able to access a patient's profile and view their symptoms and medical history (including all info from the previous forms/status updates). Medical staff should be able to raise a flag to set a profile as a high priority. They should also be able to see the patient info from the medical connector (i.e: RAMQ) and all the info from the "interactive form".
**Appointment Booking and Chat will be implemented later (they have their own epics), but will be available from this "page".

**Exit Criteria**
-Medical history of a patient should appear on their profile.
-After raising a flag on a patient's profile, the profile becomes a high priority.
-Once a medical staff visit a patient's profile, the profile should be labeled as visited in the database.

**Sub-Tasks/Steps**
- [x] Show patient's personal information
- [x] Show timeline of patients medical history updates
- [x] Redirect each patient to their own "page-status".
- [x] Allow flagging a patient as a high priority
- [x] Label a profile as visited once visited
- [x] Build UI (with a "spot" for chat and booking... will be built later on)
- [x] Write Tests
- [x]  Show a list of all patients where high priority patients appear first

**Linked to Issue**: [#42]
