### ISSUE TITLE
[USER STORY]: As a medical staff, I would like to book/recommend an appointment with a patient

### ISSUE THREAD

**Issue by fadi-albasha** [KrisTheCanadian/Protect-Together#45]
## About this story

**Priority**: Low
**Story Points**: Fibonacci Sequence: 5
**Risk**: Medium

**Description**:
Medical staff should be able to book an appointment with a patient when needed. By clicking on "recommend appointment", the patient will be prompt to choose an appointment based on the time slot. As soon as this is done, the doctor will then be able to view the appointment information in his dashboard and appointments list.

**Exit Criteria**
-Once the appointment is booked, medical staff should be able to view it on the 'My Appointments' page

**Sub-Tasks/Steps**

- [x] Create appointment and notify patient
- [x] Create UI on Figma
- [x] Write Code for UI
- [x] Write Backend Logic
- [x] Create 'My Appointments' page
- [x] Show appointment on 'My Appointments'
- [x] Add Form Validation (frontend-side/backend-side)

**Linked to Issue**: [#38]
