### ISSUE TITLE
[USER STORY]: As a medical staff (or patient), I would like to closed the file (relationship between medical staff and patient)

### ISSUE THREAD

**Issue by fadi-albasha** [KrisTheCanadian/Protect-Together#46]
## About this story

**Priority**: Low
**Story Points**: 3
**Risk**: Low

**Description**:
Medical staff and patients should be able to close a patient's file once the medical consultation finishes. When the file is closed, it will also close the case on the patients' UI view (and vice-versa).

**Exit Criteria**
-Once a file is closed, patient's database is modified to remove doctor.
-Once a file is closed, it should not appear in the medical staff list of patients.
-Once a file is closed, it should not appear in the patient info. Process re-start from scratch.

**Sub-Tasks/Steps**
- [x] Create UI 
- [x] Check if patient file can be closed (if there's upcoming appointments, cannot close file)
- [x] Remove Patient from Medical's staff table (for medical staff view).
- [x] Delete fields from firestore for Patient such as assignedDoctor, doctorName.

**Linked to Issue**: [#42 ]
