### ISSUE TITLE
[EPIC FEATURE]: 3rd-Party Dashboard

### ISSUE THREAD

**Issue by martinsenecal** [KrisTheCanadian/Protect-Together#48]
**Risk**
Medium

**Describe the solution you'd like**
The 3rd-Party Dashboard will be reserved for a "special" type of user (3rd-party). This dashboard will contain some key information about Covid. It's important to note that the "patient" data will be anonymous. Instead, this dashboard will mostly be showing data/graphics related to a high-level view of covid information (cases, tests, general symptoms, statistics on who are sick).

A 3rd-party can be a government official, a journalist, etc. Since this patient info is all confidential, there's no need to worry. They won't be able to access anything else. 

**Additional context**
<img width="863" alt="image" src="https://user-images.githubusercontent.com/38442896/160725615-19385a07-ae01-4427-ae71-5774bd0cf106.png">

**Stories/Tasks**
- [x] View Graphs with different types of data (recovery, covid tests, number of patients asking for help, etc)
- [x] Design Layout/UI
- [x] Design Tests
- [x] Add connection to data with firebase.
