### ISSUE TITLE
[USER STORY]: As a medical staff, I want to get notified when a patient book an appointment with me.

### ISSUE THREAD

**Issue by martinsenecal** [KrisTheCanadian/Protect-Together#50]
## About this story

**Priority**: [Low]
**Story Points**: Fibonacci Sequence: (3)
**Risk**: Low

**Description**:
As a medical staff, I want to get notified when I have a new appointment. I also want to make sure that the patient can only book an appointment if I give him the permission (bug)

**Exit Criteria**
What should we expect once the task is complete:
-UI is being updated (with a new countdown)
-Medical Staff is getting notified.
-Patient can only book when the doctor give him/her the permission.

**Sub-Tasks/Steps**
- [x] Create UI on Figma
- [x] Create Backend Logic
- [x] Connect Backend to UI
- [x] Fix Bug for Button Book Appointment (only enable when the doctor give permission)
- [x] Add Tests

**Additional context**

**Linked to Issue**: #19
