### ISSUE TITLE
[USER STORY]: As an admin, I want to be notified if there's un-assigned patients.

### ISSUE THREAD

**Issue by martinsenecal** [KrisTheCanadian/Protect-Together#51]
## About this story

**Priority**: [Medium]
**Story Points**: Fibonacci Sequence: (3)
**Risk**: [High]

**Description**:
In the admin dashboard, admins will need to be notified if there are more patients than the number of available slots (based on the nb of current patients and doctors). This notification will allow them to modify settings, or add more medical staff. 

There's no need to send a pop-up notification to the admin for it. A simple red dot on the UnAssigned Patients Tab is enough.

**Exit Criteria**
What should we expect once the task is complete:
-Notification Working when there is an un-assigned patient (will be in another color in the table and also notification counter will be updated)

**Sub-Tasks/Steps**

- [x] Create UI on Figma
- [x] Build Backend Logic
- [x] Connect notification to UI
- [x] Write Tests

**Additional context**

**Linked to Issue**:  #19
