### ISSUE TITLE
[USER STORY]: As a user, I would like to upload files in the chat.

### ISSUE THREAD

**Issue by martinsenecal** [KrisTheCanadian/Protect-Together#53]
## About this story

**Priority**: [Low]
**Story Points**: Fibonacci Sequence: 8
**Risk**: Low

**Description**:
Users should be able to upload files (with a max upload size) directly into the chat in order for the other user to see it.

**Exit Criteria**
What should we expect once the task is complete:
-File Uploading Form working with data validation (size, etc)
-File is Uploaded to the Cloud
-File is visible in the Chat and can be downloaded by the other user.

**Sub-Tasks/Steps**

- [ ] Add Form Validation (frontend-side/backend-side)
- [ ] Connection with Firebase Storage
- [ ] Link files to the chat as a message.
- [ ] Create UI (Figma/React)
- [ ] Add Tests

**Additional context**

**Linked to Issue**: #35
