### ISSUE TITLE
[USER STORY]: As a medical staff, I would like to be able to view my upcoming appointments.

### ISSUE THREAD

**Issue by martinsenecal** [KrisTheCanadian/Protect-Together#54]
## About this story

**Priority**: [Medium]
**Story Points**: Fibonacci Sequence: (5)
**Risk**: [Medium]

**Description**:
Medical Staff will be able to view their upcoming appointments in addition to the dashboard for convenience. 

**Exit Criteria**
What should we expect once the task is complete:
-List of Appointments for medical staff in upcoming days (and past appointments)
-Appointments are sorted by time. 

**Sub-Tasks/Steps**
- [x] Design UI on Figma
- [x] Create Button on Dashboard (and link to modal)
- [x] Design Modal (and add data from DB)
- [x] Button to delete appointment
- [x] Write Tests

**Linked to Issue**:
- #38
