### ISSUE TITLE
[USER STORY]: As an admin, I want to be able to see my list of staff in a table

### ISSUE THREAD

**Issue by martinsenecal** [KrisTheCanadian/Protect-Together#55]
## About this story

**Priority**: High
**Story Points**: 13
**Risk**: Medium

**Description**:
Admins should be able to view their staff list with some ways to search and sort results by different types of queries (type of staff, etc). They will also have an option to create new accounts (the logic is already implemented in another EPIC), however, you can prepare the UI Forms.
  
**Exit Criteria**
What should we expect once the task is complete:
-A list of staff appears in a list with different ways to sort the data.

**Sub-Tasks/Steps**

- [x] Create UI Table (with material UI)
- [x] Create Search Bar
- [x] Create Data Validation
- [x] Add Data in the Table
- [x] Add Tests

**Additional context**
This story is mostly focused on the table UI itself. Later on, we will build on top of it by adding new features (booking, notifications, timeslots, etc).

**Linked to Issue**: #27
