### ISSUE TITLE
[USER STORY]: Patients should be automatically assigned to a Medical Staff (if they ask for help)

### ISSUE THREAD

**Issue by martinsenecal** [KrisTheCanadian/Protect-Together#56]
## About this story

**Priority**: Medium
**Story Points**: Fibonacci Sequence: (8)
**Risk**: [Medium]

**Description**:
For this story, the system should automatically assign patients to a medical staff according to the medical staff slots and appointment slots. This will be part of the triage system:
- Patients will automatically be assigned to available medical staff based on their defined slots
- If no slots are available patients will be automatically be assigned to the next available slot (through the creation of another medical staff or expansion of slots or a patient case is closed).  

**Exit Criteria**
-Patient should be assigned to medical staff or be put on the waitlist.

**Sub-Tasks/Steps**

- [x] Backend Logic (Assign Patient to Medical Staff)
- [x] Add Redirection from Ask For Help to the right page (waitlisted or doctor)
- [x] Write Tests (Unit/Integration)

**Additional context**
Ask-For-Help is already done. We need to link this logic to the ask-for-help component and then redirect to the right page in the dashboard.

**Linked to Issue**: #27
