### ISSUE TITLE
[USER STORY]: Application Dashboard Layout

### ISSUE THREAD

**Issue by martinsenecal** [KrisTheCanadian/Protect-Together#57]
## About this story

**Priority**: [Low]
**Story Points**: Fibonacci Sequence: (8)
**Risk**: [Low/Medium/High]

**Description**:
Boilerplate Design of the Main View of the Dashboard (layout) for all upcoming features in it

**Exit Criteria**
What should we expect once the task is complete:
-Layout for Dashboard (with side-bar menu) is done

**Sub-Tasks/Steps**

- [x] Design UI
- [x] Build Menu Component
- [x] Build Content Component
- [x] Ensure UI is Responsive

**Additional context**

**Linked to Issue**: - #31
